Student_CourseManagement/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Student_CourseManagement.Application.Abstraction.IServices;
using Student_CourseManagement.Application.RRModels;

namespace Student_CourseManagement.API.Controllers
{
    [Route("courses")]
    public class CoursesController : Controller
    {
        private readonly ICourseServices services;

        public CoursesController(ICourseServices services)
        {
            this.services = services;
        }

        [HttpGet("add")]
        public async Task<IActionResult> AddCourse()
        {
            return View();
        }

        [HttpPost("add")]
        public async Task<IActionResult> AddCourse(CourseRequest model)
        {
            var res = await services.AddCourse(model);

            if (res == 1)
            {
                TempData["Success"] = "Course Added Successfully";
                return RedirectToAction(nameof(GetCourses));
            }
            else if (res ==0)
            {
                TempData["Error"] = "There is some error please try after sometime";
            }
            else
            {
                TempData["Error"] = "Course already exists";
            }
            return View();
        }

        [HttpGet("")]
        public async Task<IActionResult> GetCourses()
        {
            return View(await services.GetAllCouurses());
        }

        [HttpGet("update/{id}")]
        public async Task<IActionResult> UpdateCourse(Guid id)
        {
            return View(await services.GetCourseById(id));
        }
        [HttpPost("update/{id}")]
        public async Task<IActionResult> UpdateCourse(UpdateCourseRequest model)
        {
            var res = await services.UpdateCourse(model);

            if (res == 1)
            {
                TempData["Success"] = "Course updated successfully";
                return RedirectToAction(nameof(GetCourses));
            }
            else
            {
                TempData["Error"] = "There is some error please try after sometime";
            }
            return View();
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> DeleteCourse(Guid id)
        {
            var res = await services.DeleteCourse(id);

            if (res ==1)
            {
                TempData["Success"] = "Course Deleted Successfully";
            }
            else
            {
                TempData["Error"] = "There is some error please try after sometime";
            }
           return RedirectToAction(nameof(GetCourses));
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Student_CourseManagement/Controllers/StudentCoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Student_CourseManagement.Application.Abstraction.IServices;

namespace Student_CourseManagement.API.Controllers
{
    [Route("student-course")]
    public class StudentCoursesController : Controller
    {
        private readonly IStudentCourseServices services;

        public StudentCoursesController(IStudentCourseServices services)
        {
            this.services = services;
        }

        [HttpGet("")]
        public async Task<IActionResult> GetStudentCourse()
        
        {
            var studentCourse=await services.GetAllCourses();
            
            return View(studentCourse);
        }
        [HttpPost("add/{id}")]
        public async Task<IActionResult> AddStudentCourse(Guid id,Guid CourseId)
        {
           var res = await services.AddStudentCourse(id,CourseId);
            if (res == 1)
            {
                TempData["Success"] = "Student Enrolled Successfully";
            }
            else
            {
                TempData["Error"] = "There is some error please try after sometime";
            }
            return RedirectToAction(nameof(GetStudentCourse));
        }

        [HttpGet("course/{id}")]
        public async Task<IActionResult> GetStudentsByCourseId(Guid id)
        {
            var res =await services.GetStudentCourses(id);
            return View(res);
        }
        [HttpGet("delete/{id}")]
        public async Task<IActionResult> DeleteStudentFromCourse(Guid id)
        {
            var res = await services.DeleteStudentFromCourse(id);
            if (res == 1)
            {
                TempData["Success"] = "Student Removed Successfully";
            }
            else
            {
                TempData["Error"] = "There is some error please try after sometime";
            }
            return RedirectToAction(nameof(GetStudentCourse));
        }

        [HttpGet("list")]
        public async Task<IActionResult> GetAllStudentsInCourses()
        {
            return View(await services.GetAllStudentsInCourses());
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}
    }
}

Student_CourseManagement/Views/Courses/AddCourse.cshtml
@model Student_CourseManagement.Application.RRModels.CourseRequest

@{
    ViewData["Title"] = "AddCourse";
}

<h1>AddCourse</h1>
@{
    if (TempData["Error"] != null)
    {
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                Swal.fire({
                    title: 'Error!',
                    text: '@TempData["Error"]',
                    icon: 'error',
                    confirmButtonText: 'OK'
                });
            });
        </script>
    }
    else if (@TempData["Success"] != null)
    {
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                Swal.fire({
                    title: 'Success',
                    text: '@TempData["Success"]',
                    icon: 'success',
                    confirmButtonText: 'OK'
                });
            });
        </script>
    }
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCourse">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CourseName" class="control-label"></label>
                <input asp-for="CourseName" class="form-control" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Student_CourseManagement/Views/Courses/GetCourses.cshtml
@model IEnumerable<Student_CourseManagement.Application.RRModels.CourseResponse>

@{
    ViewData["Title"] = "GetCourses";
}

<h1>Courses</h1>
@{
    if (TempData["Error"] != null)
    {
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                Swal.fire({
                    title: 'Error!',
                    text: '@TempData["Error"]',
                    icon: 'error',
                    confirmButtonText: 'OK'
                });
            });
        </script>
    }
    else if (@TempData["Success"] != null)
    {
        <script>
            document.addEventListener("DOMContentLoaded", function () {
                Swal.fire({
                    title: 'Success',
                    text: '@TempData["Success"]',
                    icon: 'success',
                    confirmButtonText: 'OK'
                });
            });
        </script>
    }
}
<p>
    <a asp-action="add" asp-controller="courses" class="btn btn-success">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                    <a asp-action="UpdateCourse" asp-controller="courses" asp-route-id="@item.Id" class="btn btn-info">Edit</a>
                    <a asp-action="DeleteCourse" asp-controller="courses" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                    <a asp-action="GetStudentsByCourseId" asp-controller="StudentCourses" asp-route-id="@item.Id" class="btn btn-success">View Students</a>
               
            </td>
        </tr>
}
    </tbody>
</table>

Student_CourseManagement/Views/Courses/UpdateCourse.cshtml
@model Student_CourseManagement.Application.RRModels.CourseResponse

@{
    ViewData["Title"] = "UpdateCourse";
}

<h1>UpdateCourse</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateCourse">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CourseName" class="control-label"></label>
                <input asp-for="CourseName" class="form-control" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}